project:
  name: Example
  database: PostgreSQL
  extensionSchema: extensions
  staging:
  - staging
  dbdocs:
    base:
      exclude:
        schemas:
          - staging
          - migrate
          - extensions
    core:
      include:
        schemas:
          - core
schemas:
  - core
  - extensions
  - staging
  - migrate

extensions:
  - uuid-ossp

roles:
  - name: advanced
    refers:
      - basic
  - name: basic
tables:
  - name: core.lookups
  - name: core.lookup_values
    refers:
      - core.lookups
  - name: staging.lookup_values

views:
  - name: core.genders
    refers:
    - core.lookups
    - core.lookup_values
  - name: migrate.lookup_values
    refers:
    - core.lookups
    - core.lookup_values

import:
  options:
    truncate: true
    nullValue: ''
  tables:
  - staging.lookup_values
  after:
  - import/loader.sql

export:
  - core.lookups
  - core.lookup_values
  - core.genders
  - migrate.lookup_values
