---
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
trailingComma: none
svelteSortOrder: options-scripts-markup-styles
overrides:
  - files:
      - "*.md"
      - "*.yaml"
    options:
      useTabs: false