name: Automated Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run tests
        run: bun run test:unit
      # - name: Test & publish code coverage
      #   uses: paambaati/codeclimate-action@v3.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ef29724f55a8c015f7349da5c7a5807e00e1706c81922b2194514b93bed14397
      #   with:
      #     coverageCommand: bun coverage:lcov
      #     debug: true
      # - name: Report results to DeepSource
      #   env:
      #     DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      #   run: |
      #     curl https://deepsource.io/cli | sh
      #     ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/final.json
